//! Emit the two committed artifacts — the machine `docs/tero-index/index.json` and the
//! grep-friendly `docs/tero-index/INDEX.md` — from a sorted [`TeroIndexReport`]. Both are pure
//! functions of the report (byte-identical regeneration; the drift-gate contract), and both open
//! with the same honesty posture as `docs/api-index/INDEX.md` ("source is ground truth").
//!
//! The `INDEX.md` renders **per-family tables** (a doc's status/guarantee, an issue's
//! epic/deps/doc_refs are surfaced where they exist); `index.json` carries every field uniformly.

use std::path::Path;

use serde::Serialize;

use crate::model::{
    Family, TeroIndexItem, TeroIndexReport, HONESTY_TAG, ITEM_TAG, SIBLING_INDICES,
};

/// Write `docs/tero-index/index.json`.
///
/// # Errors
/// Any filesystem error creating `output_dir` or writing the file; a serialization error.
pub fn write_json(report: &TeroIndexReport, output_dir: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(output_dir)?;
    #[derive(Serialize)]
    struct Payload<'a> {
        generated: &'a str,
        item_tag: &'a str,
        siblings: &'a [crate::model::SiblingIndex],
        items: &'a [TeroIndexItem],
        flagged: &'a [crate::model::Flagged],
    }
    let payload = Payload {
        generated: HONESTY_TAG,
        item_tag: ITEM_TAG,
        siblings: SIBLING_INDICES,
        items: &report.items,
        flagged: &report.flagged,
    };
    let json = serde_json::to_string_pretty(&payload)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
    std::fs::write(output_dir.join("index.json"), json + "\n")
}

/// Write `docs/tero-index/INDEX.md`.
///
/// # Errors
/// Any filesystem error creating `output_dir` or writing the file.
pub fn write_markdown(report: &TeroIndexReport, output_dir: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(output_dir)?;
    let mut out = String::new();
    out.push_str("# Mycelium Tero Index — the whole-corpus citation index (Layer 1)\n\n");
    out.push_str(&format!("> **Honesty:** `{HONESTY_TAG}`\n"));
    out.push_str("> Use the index to find where to `Read`, not as an authoritative reference.\n\n");

    render_siblings(&mut out);

    for family in [
        Family::Doc,
        Family::Research,
        Family::Issue,
        Family::Changelog,
        Family::Skill,
    ] {
        let rows: Vec<&TeroIndexItem> =
            report.items.iter().filter(|i| i.family == family).collect();
        if rows.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "## {} ({} entries)\n\n",
            family.as_str(),
            rows.len()
        ));
        render_family(&mut out, family, &rows);
    }

    render_flagged(&mut out, report);

    // Exactly one trailing newline (matches api-/lib-index; a stray blank line trips MD012).
    let out = out.trim_end().to_owned() + "\n";
    std::fs::write(output_dir.join("INDEX.md"), out)
}

fn render_siblings(out: &mut String) {
    out.push_str("## Sibling indices (referenced, not duplicated)\n\n");
    out.push_str(
        "These sibling indices own their own domains and are generated by their own tools — this \
         index links to them rather than re-indexing them (DRY).\n\n",
    );
    out.push_str("| Index | Path | Covers | Regenerate |\n|---|---|---|---|\n");
    for s in SIBLING_INDICES {
        out.push_str(&format!(
            "| `{}` | `{}` | {} | `{}` |\n",
            s.name,
            s.path,
            md_escape_prose(s.covers),
            md_escape(s.generator)
        ));
    }
    out.push('\n');
}

fn render_family(out: &mut String, family: Family, rows: &[&TeroIndexItem]) {
    match family {
        Family::Doc | Family::Research => {
            out.push_str(
                "| Anchor | Kind | Id | Title | File:Line | Status | Guarantee | Summary |\n\
                 |---|---|---|---|---|---|---|---|\n",
            );
            for r in rows {
                out.push_str(&format!(
                    "| `{}` | {} | {} | {} | `{}:{}` | {} | {} | {} |\n",
                    md_escape(&r.anchor),
                    r.kind,
                    opt_code(r.id.as_deref()),
                    md_escape_prose(&r.title),
                    r.file,
                    r.line,
                    opt_plain(r.status.as_deref()),
                    opt_plain(r.guarantee_tag.as_deref()),
                    opt_prose(r.summary.as_deref()),
                ));
            }
        }
        Family::Issue => {
            out.push_str(
                "| Id | Kind | Title | File:Line | Status | Epic | Depends on | Doc refs | GH | \
                 Summary |\n|---|---|---|---|---|---|---|---|---|---|\n",
            );
            for r in rows {
                out.push_str(&format!(
                    "| `{}` | {} | {} | `{}:{}` | {} | {} | {} | {} | {} | {} |\n",
                    md_escape(&r.anchor),
                    r.kind,
                    md_escape_prose(&r.title),
                    r.file,
                    r.line,
                    opt_plain(r.status.as_deref()),
                    opt_code(r.epic.as_deref()),
                    code_list(&r.depends_on),
                    code_list(&r.doc_refs),
                    opt_code(r.gh_issue.as_deref()),
                    opt_prose(r.summary.as_deref()),
                ));
            }
        }
        Family::Changelog => {
            out.push_str(
                "| Anchor | Kind | Id | Title | File:Line | Summary |\n|---|---|---|---|---|---|\n",
            );
            for r in rows {
                out.push_str(&format!(
                    "| `{}` | {} | {} | {} | `{}:{}` | {} |\n",
                    md_escape(&r.anchor),
                    r.kind,
                    opt_code(r.id.as_deref()),
                    md_escape_prose(&r.title),
                    r.file,
                    r.line,
                    opt_prose(r.summary.as_deref()),
                ));
            }
        }
        Family::Skill => {
            out.push_str("| Anchor | Name | File:Line | Summary |\n|---|---|---|---|\n");
            for r in rows {
                out.push_str(&format!(
                    "| `{}` | {} | `{}:{}` | {} |\n",
                    md_escape(&r.anchor),
                    md_escape_prose(&r.title),
                    r.file,
                    r.line,
                    opt_prose(r.summary.as_deref()),
                ));
            }
        }
    }
    out.push('\n');
}

fn render_flagged(out: &mut String, report: &TeroIndexReport) {
    out.push_str("## Flagged items\n\n");
    out.push_str(
        "Constructs/sources the heuristic could not (or does not yet) place (G2: never silently \
         dropped):\n\n",
    );
    if report.flagged.is_empty() {
        out.push_str("*(none)*\n\n");
    } else {
        out.push_str("| Item | Reason |\n|---|---|\n");
        for f in &report.flagged {
            out.push_str(&format!(
                "| `{}` | {} |\n",
                md_escape(&f.item),
                md_escape_prose(&f.reason)
            ));
        }
        out.push('\n');
    }
}

// ── cell renderers ────────────────────────────────────────────────────────────────────────────

fn opt_code(v: Option<&str>) -> String {
    v.map(|s| format!("`{}`", md_escape(s)))
        .unwrap_or_else(|| "—".to_owned())
}

fn opt_plain(v: Option<&str>) -> String {
    v.map(md_escape_prose).unwrap_or_else(|| "—".to_owned())
}

fn opt_prose(v: Option<&str>) -> String {
    v.map(md_escape_prose).unwrap_or_else(|| "—".to_owned())
}

fn code_list(items: &[String]) -> String {
    if items.is_empty() {
        return "—".to_owned();
    }
    items
        .iter()
        .map(|s| format!("`{}`", md_escape(s)))
        .collect::<Vec<_>>()
        .join(" ")
}

/// Escape `|` for a backtick-wrapped code-span cell (code spans suppress `*`/`_`, so only `|`,
/// which would corrupt the table column syntax, needs escaping). Mirrors `lib_index::md_escape`.
pub(crate) fn md_escape(s: &str) -> String {
    s.replace('|', "\\|")
}

/// Escape `|` and `*` for a **plain-prose** cell (not code-wrapped): summary/title/flag text is
/// copied verbatim from source and may contain `|` or `*`. Deliberately does not escape `_`
/// (GFM suppresses intraword `_`, and identifiers with `_` must stay grep-able). Mirrors
/// `lib_index::md_escape_prose`.
pub(crate) fn md_escape_prose(s: &str) -> String {
    s.replace('|', "\\|").replace('*', "\\*")
}
