//! The tero-index data model — one flat, machine-readable row type over **every** corpus family,
//! plus the never-silent `flagged` list and the honesty constants (M-1015 / DN-87 §6).
//!
//! This generalizes the proven `docs/api-index/` + `docs/lib-index/` shape (a grep-friendly
//! `INDEX.md` beside a machine `index.json`, an explicit `flagged` section for extraction limits,
//! a uniform per-item honesty tag) from *one* source language (Rust symbols / `.myc` symbols) to
//! the **whole corpus**: docs (RFC/ADR/DN/spec/guides/planning), the issue tracker, the changelog,
//! research records, and the agent skills. The api-/lib-index outputs are *referenced* as sibling
//! indices ([`SIBLING_INDICES`]), never re-indexed here (DRY — they own their own domains).
//!
//! Honesty (G2/VR-5): every row is produced by the same class of line/metadata heuristic as
//! `tools/docgen/code_index.py` and `crates/mycelium-doc/src/lib_index.rs` — never a semantic
//! understanding of the source. So every row carries the *same* uniform [`ITEM_TAG`]; inventing a
//! finer per-row confidence would be an unchecked upgrade past the shared basis. Source is ground
//! truth; a construct the heuristic cannot place is a [`Flagged`] entry, never a silent drop.

use serde::{Deserialize, Serialize};

/// The top-of-file honesty grading, mirroring `docs/api-index/INDEX.md`'s header posture verbatim
/// in spirit (`Empirical/Declared — …; source is ground truth`). Rendered into the `INDEX.md`
/// header and stamped into `index.json`'s `generated` field.
///
/// No inline code-span backticks inside this string: it is itself wrapped in a single backtick
/// pair when rendered into the `INDEX.md` honesty line, and Markdown code spans do not nest (the
/// same `MD038` pitfall `lib_index.rs` documents).
pub const HONESTY_TAG: &str = "Empirical/Declared — line/metadata heuristic over the corpus \
(generalizes tools/docgen/code_index.py and mycelium-doc/src/lib_index.rs to docs/issues/changelog/\
research/skills); source is ground truth. Use this index to find where to Read, not as an \
authoritative reference.";

/// The uniform per-row honesty tag. Every row was produced by the same heuristic, so a single tag
/// is exactly as strong a claim as the extraction supports (VR-5: never invent per-row confidence
/// finer than the shared basis). Distinct from `docs/api-index/index.json`'s always-`null`
/// `guarantee_tag` placeholder — here it is populated and uniform.
pub const ITEM_TAG: &str = "Empirical/Declared";

/// The sibling indices this one deliberately does **not** duplicate — each owns its own domain and
/// is generated by its own tool. Referenced from `INDEX.md` + `index.json` so an agent knows where
/// Rust-symbol / `.myc`-symbol lookups live (M-1015: "referenced, not duplicated").
pub const SIBLING_INDICES: &[SiblingIndex] = &[
    SiblingIndex {
        name: "api-index",
        path: "docs/api-index/INDEX.md",
        covers: "Rust kernel/tooling symbols (crates/*): the mycelium-* crate public/-adjacent API.",
        generator: "tools/docgen/code_index.py (just docs-index)",
    },
    SiblingIndex {
        name: "lib-index",
        path: "docs/lib-index/INDEX.md",
        covers: "Self-hosted .myc symbols (lib/*): per-nodule fn/type/ctor of the Mycelium stdlib+compiler.",
        generator: "myc-doc lib-index (just lib-index-gen)",
    },
];

/// A pointer to a sibling index (see [`SIBLING_INDICES`]).
#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
pub struct SiblingIndex {
    /// Short name (`api-index` / `lib-index`).
    pub name: &'static str,
    /// The committed `INDEX.md` path, repo-relative.
    pub path: &'static str,
    /// One line: what domain that index owns (and this one therefore leaves to it).
    pub covers: &'static str,
    /// How that index is regenerated.
    pub generator: &'static str,
}

/// Which corpus family a row was extracted from (drives grouping in `INDEX.md` + a stable primary
/// sort key). A closed set: a source that fits none of these is out of scope and *recorded as such*
/// (never silently indexed under the wrong family).
///
/// `Deserialize` (M-1016): [`crate::load::load_report`] reads a previously emitted `index.json`
/// back into a [`TeroIndexReport`] for the query engine (the read-side twin of
/// [`crate::emit::write_json`]'s write) rather than re-walking the corpus per query.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Family {
    /// A markdown document under `docs/` (RFC/ADR/DN/spec/guide/planning/other) or one of its
    /// sections.
    Doc,
    /// A research record under `research/` or one of its sections.
    Research,
    /// A task/epic entry in `tools/github/issues.yaml`.
    Issue,
    /// A `CHANGELOG.md` release header or dated entry.
    Changelog,
    /// An agent skill (`.claude/skills/*/SKILL.md`).
    Skill,
}

impl Family {
    /// The canonical label (also the `INDEX.md` section grouping key).
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Family::Doc => "doc",
            Family::Research => "research",
            Family::Issue => "issue",
            Family::Changelog => "changelog",
            Family::Skill => "skill",
        }
    }
}

/// One indexed row: a citable unit of the corpus with its provenance, status/tag where the source
/// carries one, and a one-line summary **extracted verbatim-ish from source, never invented** (the
/// apiref "projection, not authorship" posture).
///
/// The family-specific fields (`epic` / `depends_on` / `doc_refs` / `gh_issue`) are populated only
/// for the family that has them (issues) and skipped in JSON when empty — a lean, deterministic
/// serialization.
///
/// `Deserialize` (M-1016): round-trips through [`crate::emit::write_json`] /
/// [`crate::load::load_report`] so the query engine reads the committed artifact directly.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TeroIndexItem {
    /// A stable, globally-unique citation anchor (GitHub-style slug via `mycelium_doc::corpus`,
    /// or the source's own id for issues). Deep links + cross-platform citation hang off this.
    pub anchor: String,
    /// The corpus family.
    pub family: Family,
    /// The family-specific kind (`rfc`/`adr`/`note`/`spec`/`section` for docs, `issue`/`epic` for
    /// the tracker, `release`/`entry` for the changelog, `skill`, `record`/`section` for research).
    pub kind: String,
    /// The source's own id where it has one (`RFC-0034`, `ADR-032`, `DN-87`, `M-1015`, `E39-1`);
    /// `None` for a raw section/heading with no id of its own.
    ///
    /// `#[serde(default)]` (M-1016): every emitted `index.json` omits this key when `None`
    /// (`skip_serializing_if`), so [`crate::load::load_report`] must tolerate a missing key rather
    /// than erroring — the write-omit and the read-default are the same "`None` is not a missing
    /// field" contract, on both sides of the round trip. Applied to every optional/`Vec` field below
    /// for the same reason.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub id: Option<String>,
    /// The display title / heading / issue title / skill name.
    pub title: String,
    /// Repo-relative source path.
    pub file: String,
    /// 1-based source line.
    pub line: u32,
    /// The declared status where the source has one (a doc `Status` row's leading lattice keyword,
    /// an issue's `status:` label); `None` when the source carries none.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub status: Option<String>,
    /// The guarantee tag of the cited claim where the source declares one (a doc `Guarantee` row's
    /// leading `Exact`/`Proven`/`Empirical`/`Declared`); `None` otherwise. This is the *cited*
    /// claim's tag, distinct from [`TeroIndexItem::tag`] (this row's own extraction honesty).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub guarantee_tag: Option<String>,
    /// A one-line summary, verbatim-ish from source (truncated, never invented — G2); `None` is an
    /// explicit "no summary in source" gap, not a missing field.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub summary: Option<String>,
    /// Issues only: the parent epic id.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub epic: Option<String>,
    /// Issues only: the `depends_on` task ids.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub depends_on: Vec<String>,
    /// Issues only: the `doc_refs` citation strings.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub doc_refs: Vec<String>,
    /// Issues only: the GitHub issue number, resolved from `tools/github/idmap.tsv` where present.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub gh_issue: Option<String>,
    /// The extraction honesty tag ([`ITEM_TAG`]) — populated + uniform, not a placeholder.
    pub tag: String,
}

impl TeroIndexItem {
    /// A minimal row with the shared honesty tag set and every family-specific field empty. Family
    /// extractors fill `status`/`guarantee_tag`/`summary`/the issue fields as their source affords.
    #[must_use]
    pub fn new(
        anchor: impl Into<String>,
        family: Family,
        kind: impl Into<String>,
        title: impl Into<String>,
        file: impl Into<String>,
        line: u32,
    ) -> Self {
        TeroIndexItem {
            anchor: anchor.into(),
            family,
            kind: kind.into(),
            id: None,
            title: strip_md_links(&title.into()),
            file: file.into(),
            line,
            status: None,
            guarantee_tag: None,
            summary: None,
            epic: None,
            depends_on: Vec::new(),
            doc_refs: Vec::new(),
            gh_issue: None,
            tag: ITEM_TAG.to_owned(),
        }
    }
}

/// Reduce embedded markdown-link markup `[text](target)` to just its `text`, leaving all other
/// text verbatim. Applied to every indexed title/summary because a corpus **section heading** can
/// itself contain a relative cross-link (e.g. `4. Guarantee matrix — [RFC-0016 §4.5](../../rfcs/…)`);
/// copied verbatim into `docs/tero-index/INDEX.md` that relative target no longer resolves from the
/// index's location, so the offline `links` gate (correctly) flags it as broken. Keeping the link
/// *text* and dropping the *plumbing* is the honest projection for an index cell — the citable
/// location is already the row's own anchor + `file:line`, not the incidental in-heading link. A
/// bracket run that is not a well-formed link is copied through unchanged (never a lossy guess).
pub(crate) fn strip_md_links(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = String::with_capacity(s.len());
    let mut i = 0;
    while i < s.len() {
        if bytes[i] == b'[' {
            // A link is `[` text `]` `(` target `)`, all four delimiters ASCII (byte-safe finds).
            if let Some(close) = s[i + 1..].find(']') {
                let text_end = i + 1 + close;
                if bytes.get(text_end + 1) == Some(&b'(') {
                    if let Some(paren) = s[text_end + 2..].find(')') {
                        out.push_str(&s[i + 1..text_end]); // the link text only
                        i = text_end + 2 + paren + 1; // skip past the closing `)`
                        continue;
                    }
                }
            }
        }
        // Not a link start — copy one whole char (UTF-8 safe).
        let ch = s[i..].chars().next().unwrap();
        out.push(ch);
        i += ch.len_utf8();
    }
    out
}

/// A construct/source the heuristic could not (or does not yet) place — recorded, never dropped
/// (G2). Mirrors `lib_index::Flagged`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Flagged {
    /// What the flag is about (a path, an id, a `"<source> (line N)"` locator).
    pub item: String,
    /// Why it is flagged, in author-facing terms.
    pub reason: String,
}

/// The full build result: every extracted row plus every flagged gap, in stable sorted order.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct TeroIndexReport {
    /// The indexed rows.
    pub items: Vec<TeroIndexItem>,
    /// The never-silent extraction gaps.
    pub flagged: Vec<Flagged>,
}

impl TeroIndexReport {
    /// Sort rows + flags into the canonical, deterministic order (the byte-identical-regeneration
    /// contract, DN-87 §6.3). Rows sort by `(family, file, line, anchor)`; flags by `(item,
    /// reason)`. A total order over all-comparable keys ⇒ a stable serialization.
    pub fn sort(&mut self) {
        self.items.sort_by(|a, b| {
            (a.family, &a.file, a.line, &a.anchor).cmp(&(b.family, &b.file, b.line, &b.anchor))
        });
        self.flagged
            .sort_by(|a, b| a.item.cmp(&b.item).then_with(|| a.reason.cmp(&b.reason)));
    }
}
